"""CIS Azure 8.1.5.2 – Ensure Advanced Threat Protection Alerts for Storage Accounts Are Monitored (Manual, L1)"""
from __future__ import annotations

from sspm.core.models import AssessmentStatus, CISControl, CISProfile, RuleMetadata, Severity
from sspm.core.registry import registry
from sspm.providers.azure.rules.base import AzureRule
from sspm.providers.base import CollectedData


@registry.rule
class CIS_8_1_5_2(AzureRule):
    metadata = RuleMetadata(
        id="azure-cis-8.1.5.2",
        title="Ensure Advanced Threat Protection Alerts for Storage Accounts Are Monitored",
        section="8.1.5 Defender Plan: Storage",
        benchmark="CIS Microsoft Azure Foundations Benchmark v6.0.0",
        assessment_status=AssessmentStatus.MANUAL,
        profiles=[CISProfile.AZURE_L1],
        severity=Severity.MEDIUM,
        description=(
            "Advanced Threat Protection (ATP) alerts generated by Defender for Storage must be "
            "actively monitored and triaged by security operations to ensure timely response to "
            "suspicious storage activity."
        ),
        rationale=(
            "Enabling Defender for Storage alone is insufficient if alerts are not reviewed. "
            "Unmonitored alerts allow data exfiltration or ransomware staging to proceed "
            "undetected even when telemetry is available."
        ),
        impact="None — this is a process control.",
        audit_procedure=(
            "Verify that a process exists to regularly review Defender for Cloud alerts "
            "related to Storage Accounts, and that alert suppression rules do not silently "
            "discard storage-related findings."
        ),
        remediation=(
            "Defender for Cloud → Security alerts → filter by Resource type: Storage → "
            "review and triage all open alerts. Establish an alerting pipeline (e.g. Logic App "
            "or SIEM integration) for storage ATP alerts."
        ),
        default_value="Alerts are generated but not monitored by default.",
        references=[
            "https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-introduction",
        ],
        cis_controls=[
            CISControl(version="v8", control_id="13.1", title="Centralize Security Event Alerting", ig1=False, ig2=True, ig3=True),
        ],
    )

    async def check(self, data: CollectedData) -> "Finding":
        return self._skip(
            "This control requires manual verification: confirm that a process exists to "
            "monitor and triage Defender for Storage ATP alerts in the Azure portal or SIEM."
        )
